### ISSUE TITLE
[Horoscope][Aurascan][Tokens][CW-20] Not display Read/Write contract tabs with contract has latest version

### ISSUE THREAD

**Issue by ntatfff** [aura-nw/horoscope#218]
**Bug description:** Not display Read/Write contract tabs with contract has latest version (Verified this contract successfully)

**Link:** https://serenity.aurascan.io/contracts/aura1x49tp4m07nneryr8hjum04rv0a4t9r07ma5dkdnn72dhtlr5vk7qmsuvgn

**Expected result:** Display Read/Write contract tabs with contract has latest version
![image](https://user-images.githubusercontent.com/24869170/211261724-5bd3d6f8-f4fa-4d3e-ba95-1c5bc1ad9008.png)

**Comment by doquockhanhan** [comment]
closing this issue since it is done.
